apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
data:
  dashboards.yaml: |
    apiVersion: 1

    providers:
      - name: dashboards
        type: file
        updateIntervalSeconds: 30
        options:
          path: /etc/grafana/dashboards
          foldersFromFilesStructure: true
  datasource.yaml: |
    apiVersion: 1

    deleteDatasources:
      - name: Prometheus
        orgId: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus:9090
        password:
        user:
        database:
        basicAuth: true
        basicAuthUser: admin
        basicAuthPassword: foobar
        withCredentials:
        isDefault: true
        jsonData:
          graphiteVersion: "1.1"
          tlsAuth: false
          tlsAuthWithCACert: false
        secureJsonData:
          tlsCACert:
          tlsClientCert:
          tlsClientKey:
        version: 1
        editable: true
